"""init

Revision ID: 07758bdcb0d1
Revises: 
Create Date: 2023-08-27 12:15:52.323733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07758bdcb0d1'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique ID'),
    sa.Column('name', sa.String(), nullable=True, comment='Name'),
    sa.Column('lastname', sa.String(), nullable=True, comment='Lastname'),
    sa.Column('role', sa.Boolean(), nullable=True, comment='Users role'),
    sa.PrimaryKeyConstraint('id'),
    schema='test_name',
    comment='User of system'
    )
    op.create_table('emotion',
    sa.Column('id', sa.Integer(), nullable=False, comment='Unique ID'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Сборщик эмоций'),
    sa.Column('anger', sa.Integer(), nullable=True),
    sa.Column('fear', sa.Integer(), nullable=True),
    sa.Column('happy', sa.Integer(), nullable=True),
    sa.Column('neutral', sa.Integer(), nullable=True),
    sa.Column('sadness', sa.Integer(), nullable=True),
    sa.Column('surprized', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['test_name.user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    schema='test_name',
    comment='Emotions metrics'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('emotion', schema='test_name')
    op.drop_table('user', schema='test_name')
    # ### end Alembic commands ###
