"""add_sex

Revision ID: d095d6e42aff
Revises: 1fc068ce2dde
Create Date: 2023-09-09 05:18:41.357426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd095d6e42aff'
down_revision: Union[str, None] = '1fc068ce2dde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotion', sa.Column('worker_id', sa.Integer(), nullable=False, comment='Сборщик эмоций'), schema='test_name')
    op.add_column('emotion', sa.Column('sex', sa.Boolean(), nullable=True), schema='test_name')
    op.drop_constraint('emotion_user_id_fkey', 'emotion', schema='test_name', type_='foreignkey')
    op.create_foreign_key(None, 'emotion', 'user', ['worker_id'], ['id'], source_schema='test_name', referent_schema='test_name', ondelete='CASCADE')
    op.drop_column('emotion', 'user_id', schema='test_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('emotion', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False, comment='Сборщик эмоций'), schema='test_name')
    op.drop_constraint(None, 'emotion', schema='test_name', type_='foreignkey')
    op.create_foreign_key('emotion_user_id_fkey', 'emotion', 'user', ['user_id'], ['id'], source_schema='test_name', referent_schema='test_name', ondelete='CASCADE')
    op.drop_column('emotion', 'sex', schema='test_name')
    op.drop_column('emotion', 'worker_id', schema='test_name')
    # ### end Alembic commands ###
